### ISSUE TITLE
Way to draw text

### ISSUE THREAD

**Issue by figsoda** [bread-graphics/breadx#56]
is there any function to draw text with breadx?

quick search gave me [`xcb_image_text_8`](https://www.x.org/releases/current/doc/man/man3/xcb_image_text_8.3.xhtml)

**Comment by notgull** [comment]
The proper way of drawing text is to load whichever font you want (I've found [rusttype](https://crates.io/crates/rusttype) to be a good tool for this), convert whichever glyphs you want to draw into [images](https://docs.rs/breadx/1.2.0/breadx/image/struct.Image.html), convert those images into `Pixmap`s with [`create_pixmap_from_image`](https://docs.rs/breadx/1.2.0/breadx/display/traits/trait.DisplayDrawableExt.html#method.create_pixmap_from_image), and use [`copy_area`](https://docs.rs/breadx/1.2.0/breadx/display/traits/trait.DisplayDrawableExt.html#method.copy_area) to copy those glyph-images onto your window or pixmap or what-have-you.

Yes, the `xcb_image_text_8` request has an [equivalent](https://docs.rs/breadx/1.2.0/breadx/auto/xproto/struct.ImageText8Request.html) in `breadx`, but I haven't gotten around to implementing a convenience method for using it. This is partly because the breadth of the X11 API is exhausting to implement in its entirety, and partly because the native string drawing API is counterproductive to use. It uses a font format that no one else uses and is generally hard to port to other platforms. No serious application has used it since the 90's.

That being said, if this is not a serious application, I cannot stop you from doing:

```
use breadx::auto::xproto::ImageText8Request;
let text = String::from("This is the text I want to draw");
let request = ImageText8Request {
    drawable: win.into(),
    gc,
    x: 10,
    y: 10,
    string: text.into(),
    ..Default::default()
};
conn.exchange_request(request)?;
```
